language: python
# pick the appropriate requirements file for 2.7 or 3.x
matrix:
  include:
    - python: "2.7"
      env: REQUIREMENTS=requirements2.txt
    - python: "3.5"
      env: REQUIREMENTS=requirements.txt
    - python: "3.6"
      env: REQUIREMENTS=requirements.txt
# install system dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential muscle mafft cd-hit
# command to install dependencies
install:
  - pip install -r $REQUIREMENTS
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
