language: python
# versions and requirements files
matrix:
  include:
    - python: "3.6"
      env: REQUIREMENTS=requirements.txt
    - python: "3.7"
      env: REQUIREMENTS=requirements.txt
    - python: "3.8"
      env: REQUIREMENTS=requirements.txt
# install system dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential muscle mafft cd-hit
# command to install dependencies
install:
  - pip install -r $REQUIREMENTS
  - pip install abstar
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
